# Generated by Django 4.2.18 on 2025-02-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphoki', '0003_playerscore_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerscore',
            name='game',
            field=models.CharField(choices=[('flippy', 'Flippy Hoki'), ('pixeldroid', 'PixelDroid')], max_length=20),
        ),
    ]
